blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/EvHaus/react-pdf-charts/discussions
    about: Use GitHub discussions for message-board style questions and discussions.